# Desafio Numero 4 de Programación y analisís de datos con Python
Por Matias Barra

## - Desarrollo

### - Sector de Librerias

In [2]:
import pandas as pd

### - Leer Data set

In [4]:
url_archivo = "C:\\Users\\Matias\\Downloads\\resumen_resultados_astronautas.csv" # ruta del archivo, importante separar por doble \\
df = pd.read_csv(url_archivo) #leemos y asigamos el Data frame a la variable df

In [12]:
df.head() # miramos que hay dentro de df

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica
0,Alana Morillo,32,75,180,93,88,78,89,6,Si
1,Fátima Tafalla,27,68,167,82,95,81,87,4,Si
2,Sofía Puig,29,80,185,85,80,90,91,3,Si
3,Valentina Tasis,30,65,175,90,91,85,92,2,No
4,Regina Cicerón,31,76,183,89,87,83,90,7,Si

In [11]:
df.shape # un resumen de los datos dentro de df

(32, 10)

### - Transformación y manipulación de columnas

Transformamos la altura de cm a metros para conseguir valores reales del IMC. y creamos la columna IMC.

In [19]:
df["IMC"] = df["peso"] / ((df["altura"]/100)**2) # formula de IMC en caso de que altura este en CM.

In [20]:
df.head()

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC
0,Alana Morillo,32,75,180,93,88,78,89,6,Si,23.148148
1,Fátima Tafalla,27,68,167,82,95,81,87,4,Si,24.382373
2,Sofía Puig,29,80,185,85,80,90,91,3,Si,23.374726
3,Valentina Tasis,30,65,175,90,91,85,92,2,No,21.224490
4,Regina Cicerón,31,76,183,89,87,83,90,7,Si,22.694019

Creamos columna Promedio Evaluación la cual tomara las evaluaciones fisicas, psicologicas, adaptativas y medicas de cada registro.

In [21]:
cols_eval = ["evaluacion_fisica", "evaluacion_psicologica", "evaluacion_adaptativa", "evaluacion_medica"] # seleccionamos las columnas que ocuparemos
df["promedio_evaluaciones"] = df[cols_eval].mean(axis=1) #creamos columna promedio_evaluaciones con .mean que es la funcion de promedio

In [22]:
df.head() #miramos de nuevo como salio la transformación

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones
0,Alana Morillo,32,75,180,93,88,78,89,6,Si,23.148148,87.00
1,Fátima Tafalla,27,68,167,82,95,81,87,4,Si,24.382373,86.25
2,Sofía Puig,29,80,185,85,80,90,91,3,Si,23.374726,86.50
3,Valentina Tasis,30,65,175,90,91,85,92,2,No,21.224490,89.50
4,Regina Cicerón,31,76,183,89,87,83,90,7,Si,22.694019,87.25

In [23]:
df_filtrado = df[ ## creamos un df diferente para incluir las registros filtrados
    (df["IMC"].between(18.5, 24.9)) &
    (df["promedio_evaluaciones"] >= 87) #la condicion busca los IMc entre 18.5 y 24.9, para luego evaluar su promedio
]

In [24]:
df_filtrado = df_filtrado.reset_index(drop=True) #reiniciamos los indices del Df ya que con el filtrado ya no se hace fiable su uso.

In [25]:
df_filtrado.head() #visualizamos nuevo df_filtrado

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones
0,Alana Morillo,32,75,180,93,88,78,89,6,Si,23.148148,87.00
1,Valentina Tasis,30,65,175,90,91,85,92,2,No,21.224490,89.50
2,Regina Cicerón,31,76,183,89,87,83,90,7,Si,22.694019,87.25
3,María Juderías,28,78,182,88,85,87,92,5,Si,23.547881,88.00
4,Consuela Arboleda,33,77,188,94,83,89,93,8,Si,21.785876,89.75

In [26]:
df_filtrado.shape #vemos cuants registros quedaron

(12, 12)

In [27]:
df_filtrado["califica"] = "Si" # cambiamos los datos de columna califica a si, dado que deberia calificar.

In [29]:
df_filtrado.head(12) # volvemos a visualizar la transformación

,nombre,edad,peso,altura,evaluacion_fisica,evaluacion_psicologica,evaluacion_adaptativa,evaluacion_medica,anos_experiencia,califica,IMC,promedio_evaluaciones
0,Alana Morillo,32,75,180,93,88,78,89,6,Si,23.148148,87.00
1,Valentina Tasis,30,65,175,90,91,85,92,2,Si,21.224490,89.50
2,Regina Cicerón,31,76,183,89,87,83,90,7,Si,22.694019,87.25
3,María Juderías,28,78,182,88,85,87,92,5,Si,23.547881,88.00
4,Consuela Arboleda,33,77,188,94,83,89,93,8,Si,21.785876,89.75
5,Patricio Encarnación,30,81,190,93,86,88,91,4,Si,22.437673,89.50
6,Cristóbal Miralles,31,72,174,88,91,86,92,6,Si,23.781213,89.25
7,Nicolás Cambeiro,29,68,175,88,90,81,90,2,Si,22.204082,87.25
8,Samuel Gálvez,22,74,183,91,91,91,86,3,Si,22.096808,89.75
9,Christopher Berganza,23,70,173,92,93,92,85,1,Si,23.388687,90.50
10,Alexia Gaos,21,69,169,93,94,93,86,0,Si,24.158818,91.50
11,Fátima Varela,33,73,182,91,90,91,88,5,Si,22.038401,90.00

### -  Exportación a CSV

In [30]:
df_filtrado.to_csv("astronautas_calificados.csv", index=False) #se guardara en la misma carpeta donde se encuentre alojado el notebook por defecto.
print("Archivo 'astronautas_calificados.csv' exportado con exito")