# <span style="color: green;"> Desafío - Manipulación y transformación de datos (P1) </span>

por Matias Barra

## <span style="color: green;"> a.</span> Carga los datos y crea un DataFrame con cada uno de ellos

## <span style="color: blue;"> Sector de Imports y rutas</span>

In [4]:
import pandas as pd
import numpy as np

Leer Archivos pkl con read_pickle sin agregar ruta exacta, hay que asegurarse que los archivos esten en la misma carpeta que el notebook.

ademas pandas ya tiene una funcion para leer tanto archivos pkl como csv, por lo que no necesitamos llamar una libreria especifica.

In [7]:
df_subjects = pd.read_pickle("subjects.pkl") #verificar que ambos nombres son iguales (archivos y ruta)
df_incidents = pd.read_pickle("incidents.pkl")
df_officers = pd.read_pickle("officers.pkl")
df_jobs = pd.read_csv("Cleaned_DS_Jobs.csv") #este de aqui es csv, por lo que utilizamos read_csv

Mostramos los df creados y verificamos su correcta ejecucion

* <span style="color: blue;"> DataFrame: subjects </span>

In [13]:
df_subjects.head()

  case_number race gender last_name first_name        full_name
0      44523A    L      M     Curry      James     Curry, James
1     121982X    L      M    Chavez    Gabriel  Chavez, Gabriel
2     605484T    L      M   Salinas       Nick    Salinas, Nick
3     384832T    B      M     Smith      James     Smith, James
4     384832T    B      M      Dews    Antonio    Dews, Antonio

In [15]:
df_subjects.shape

(223, 6)

* <span style="color: blue;"> DataFrame: incidents </span>

In [10]:
df_incidents.head()

,case_number,date,location,subject_statuses,subject_weapon,subjects,subject_count,officers,officer_count,grand_jury_disposition,attorney_general_forms_url,summary_url,summary_text,latitude,longitude
0,44523A,2013-02-23,3000 Chihuahua Street,Injured,Handgun,"Curry, James L/M",1,"Patino, Michael L/M; Fillingim, Brian W/M",2,No Bill,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, February 23, 2013, at approximate...",NaN,NaN
1,121982X,2010-05-03,1300 N. Munger Boulevard,Injured,Handgun,"Chavez, Gabriel L/M",1,"Padilla, Gilbert L/M",1,No Bill,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Monday, May 3, 2010, at approximately 8:06 ...",NaN,NaN
2,605484T,2007-08-12,200 S. Stemmons Freeway,Other,Shotgun,"Salinas, Nick L/M",1,"Poston, Jerry W/M",1,See Summary,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Sunday, August 12, 2007, at approximately 2...",NaN,NaN
3,384832T,2007-05-26,7900 S. Loop 12,Shoot and Miss,Unarmed,"Smith, James B/M; Dews, Antonio B/M; Spearman,...",3,"Mondy, Michael B/M",1,None,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Saturday, May 26, 2007, at approximately 1:...",NaN,NaN
4,244659R,2006-04-03,6512 South Loop 12,Injured,Hands,"Watkins, Caleb B/M",1,"Armstrong, Michael W/M",1,No Bill,None,http://dallaspolice.net/reports/OIS/narrative/...,"On Monday, April 3, 2006, at approximately 11:...",NaN,NaN

In [16]:
df_incidents.shape

(219, 15)

* <span style="color: blue;"> DataFrame: officers </span>

In [17]:
df_officers.head()

  case_number race gender  last_name first_name         full_name
0      44523A    L      M     Patino    Michael   Patino, Michael
1      44523A    W      M  Fillingim      Brian  Fillingim, Brian
2     121982X    L      M    Padilla    Gilbert  Padilla, Gilbert
3     605484T    W      M     Poston      Jerry     Poston, Jerry
4     384832T    B      M      Mondy    Michael    Mondy, Michael

In [18]:
df_officers.shape

(370, 6)

* <span style="color: blue;"> DataFrame: jobs </span>

In [19]:
df_jobs.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,company_age,python,excel,hadoop,spark,aws,tableau,big_data,job_simp,seniority
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,Nonprofit Organization,Insurance Carriers,...,27,0,0,0,0,1,0,0,data scientist,senior
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,Company - Public,Research & Development,...,52,0,0,1,0,0,0,1,data scientist,na
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,Private Practice / Firm,Consulting,...,39,1,1,0,0,1,0,0,data scientist,na
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,Company - Public,Electrical & Electronic Manufacturing,...,20,1,1,0,0,1,0,0,data scientist,na
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,Company - Private,Advertising & Marketing,...,22,1,1,0,0,0,0,0,data scientist,na

In [20]:
df_jobs.shape

(660, 27)

## <span style="color: green;"> b.</span> Genera una tabla que contenga la unión de las 3 tablas officer, subjects y incidents.

Primero, seleccionamos 2 df y las unimos en 1 solo merge, dadoque pandas no puede trabajar con mas de dos df a la vez, y utilizamos la columna clave que comparten nuestras df: case_number

In [47]:
df_incidents_officers = pd.merge(
    df_incidents,                 # tabla base
    df_officers,                  # tabla a unir
    on="case_number",          # columna en comun/columna clave
    how="left",                # conserva todos los incidents, aunque no haya oficiales
    suffixes=("", "_officers") # agrega sufijo a columnas de officers que se repitan en incidents.
)

In [48]:
df_incidents_officers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 370 entries, 0 to 369
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   case_number                 370 non-null    object
 1   date                        370 non-null    object
 2   location                    370 non-null    object
 3   subject_statuses            370 non-null    object
 4   subject_weapon              370 non-null    object
 5   subjects                    370 non-null    object
 6   subject_count               370 non-null    int64
 7   officers                    370 non-null    object
 8   officer_count               370 non-null    int64
 9   grand_jury_disposition      258 non-null    object
 10  attorney_general_forms_url  5 non-null      object
 11  summary_url                 356 non-null    object
 12  summary_text                356 non-null    object
 13  latitude                    360 non-null    float64
 14  longitude                   360 non-null    float64
 15  race                        366 non-null    object
 16  gender                      370 non-null    object
 17  last_name                   370 non-null    object
 18  first_name                  367 non-null    object
 19  full_name                   370 non-null    object
dtypes: float64(2), int64(2), object(16)
memory usage: 57.9+ KB

 Ahora unimos el resultado con subjects (también por 'case_number')

In [58]:
df_merged_data = pd.merge(
    df_incidents_officers,        # lo que ya unimos
    df_subjects,                  # tabla de sujetos
    on="case_number",          # columna comun/columna clave
    how="left",                 # mismo tipo de join
    suffixes=("", "_subject")  # agrega sufijo a columnas de subjects que se repitan en incidents_officers
)

Verificamos que el df_merged_data se puede visualizar.

In [44]:
df_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   case_number                 380 non-null    object
 1   date                        380 non-null    object
 2   location                    380 non-null    object
 3   subject_statuses            380 non-null    object
 4   subject_weapon              380 non-null    object
 5   subjects                    380 non-null    object
 6   subject_count               380 non-null    int64
 7   officers                    380 non-null    object
 8   officer_count               380 non-null    int64
 9   grand_jury_disposition      265 non-null    object
 10  attorney_general_forms_url  5 non-null      object
 11  summary_url                 366 non-null    object
 12  summary_text                366 non-null    object
 13  latitude                    368 non-null    float64
 14  longitude                   368 non-null    float64
 15  race                        376 non-null    object
 16  gender                      380 non-null    object
 17  last_name                   380 non-null    object
 18  first_name                  377 non-null    object
 19  full_name                   380 non-null    object
 20  race_subject                377 non-null    object
 21  gender_subject              377 non-null    object
 22  last_name_subject           377 non-null    object
 23  first_name_subject          345 non-null    object
 24  full_name_subject           377 non-null    object
dtypes: float64(2), int64(2), object(21)
memory usage: 74.3+ KB

## <span style="color: green;"> c.</span> Verifica si hay filas duplicadas; si es así, elimínalas

Contamos cuantas filas duplicadas existen en el DataFrame unido

In [50]:
duplicados = df_merged_data.duplicated().sum()
print(f"Filas duplicadas encontradas: {duplicados}")

Filas duplicadas encontradas: 0

no hay duplicadas en si (dado que el registro tiene 24 columnas y es dificil que se repita el mismo registro, lo que podemos hacer es condicionar que el conteo de los duplicados se enfoque en columnas especificas)

In [59]:
duplicados = df_merged_data.duplicated(subset=["case_number", "full_name", "full_name_subject"]).sum() ## buscamos registros cuyo case_number, full_name y full_name_subject sean igual
print(f"Filas duplicadas encontradas: {duplicados}")

Filas duplicadas encontradas: 1

Ahora eliminamos filas duplicadas, en si comparamos que el numero de caso en cuestion no tenga el mismo nombre asociado tanto en officer como en subject.

In [60]:
df_merged_data = df_merged_data.drop_duplicates(subset=["case_number", "full_name", "full_name_subject"])

In [61]:
df_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 379 entries, 0 to 379
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   case_number                 379 non-null    object
 1   date                        379 non-null    object
 2   location                    379 non-null    object
 3   subject_statuses            379 non-null    object
 4   subject_weapon              379 non-null    object
 5   subjects                    379 non-null    object
 6   subject_count               379 non-null    int64
 7   officers                    379 non-null    object
 8   officer_count               379 non-null    int64
 9   grand_jury_disposition      265 non-null    object
 10  attorney_general_forms_url  5 non-null      object
 11  summary_url                 365 non-null    object
 12  summary_text                365 non-null    object
 13  latitude                    367 non-null    float64
 14  longitude                   367 non-null    float64
 15  race                        375 non-null    object
 16  gender                      379 non-null    object
 17  last_name                   379 non-null    object
 18  first_name                  376 non-null    object
 19  full_name                   379 non-null    object
 20  race_subject                376 non-null    object
 21  gender_subject              376 non-null    object
 22  last_name_subject           376 non-null    object
 23  first_name_subject          345 non-null    object
 24  full_name_subject           376 non-null    object
dtypes: float64(2), int64(2), object(21)
memory usage: 77.0+ KB

## <span style="color: green;"> d.</span> ¿Cuántos sujetos de género F hay en el DataFrame resultante?

In [62]:
# Contar sujetos de género F
cantidad_f = (df_merged_data["gender_subject"] == "F").sum()
print(f"Cantidad de sujetos de género F: {cantidad_f}")

cantidad_f = (df_merged_data["gender"] == "F").sum()
print(f"Cantidad de género F: {cantidad_f}")

Cantidad de sujetos de género F: 8
Cantidad de género F: 19

## <span style="color: green;"> e.</span> ¿En cuántos números de caso hay por lo menos una sospechosa que sea mujer?

primero, filtramos los sospechosos cuyo genero sea f

In [63]:
sospechosas = df_merged_data[df_merged_data["gender"] == "F"]

Extraer los números de caso únicos donde hay al menos una mujer

In [65]:
casos_con_mujeres = sospechosas["case_number"].unique()
cantidad_casos = len(casos_con_mujeres) #usamos len para medir la longitud de df que nos queda al filtrar los casos unicos de sospechosos
print(f"Hay {cantidad_casos} casos con al menos una sospechosa mujer.")

Hay 17 casos con al menos una sospechosa mujer.

## <span style="color: green;"> f.</span> Genera una tabla pivote que muestre en las filas el género del oficial y en las columnas el género del subject. ¿Cómo interpretas los valores que muestra esta vista?

In [70]:
tabla_pivote = pd.pivot_table(
    df_merged_data,
    index="gender",   # filas: género del oficial
    columns="gender_subject", # columnas: genero del sujeto
    values="case_number",     # cualquier valor (solo para contar)
    aggfunc="count",          # función de agregación → cuenta cuántos casos hay
    fill_value=0              # reemplaza NaN por 0
)

In [68]:
tabla_pivote.head

gender_subject  F    M
gender
F               1   18
M               7  350

Tomando en cuenta que los datos ocupados representan a personas envueltas en incidentes de diferentes grados de lesiones, podemos interpretar en esta tabla que en gran medida tanto oficiales como sujetos pertenecen al genero masculino, ademas que en caso de oficiales mujeres envueltas en incidentes son mucho menor que los casos masculinos. por lo tanto en este tipo de analisis podemos decir que el genero masculino esta involucrado en muchos mas incidentes que el genero femenino.

# <span style="color: green;"> Desafío - Manipulación y transformación de datos (P2) </span>

Para continuar con el desarrollo de este desafío, necesitarás el archivos
Cleaned_DS_Jobs.csv

## <span style="color: green;"> a.</span> Carga los datos y crea un DataFrame con ellos

In [71]:
df_jobs.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,company_age,python,excel,hadoop,spark,aws,tableau,big_data,job_simp,seniority
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,Nonprofit Organization,Insurance Carriers,...,27,0,0,0,0,1,0,0,data scientist,senior
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,Company - Public,Research & Development,...,52,0,0,1,0,0,0,1,data scientist,na
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,Private Practice / Firm,Consulting,...,39,1,1,0,0,1,0,0,data scientist,na
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,Company - Public,Electrical & Electronic Manufacturing,...,20,1,1,0,0,1,0,0,data scientist,na
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,Company - Private,Advertising & Marketing,...,22,1,1,0,0,0,0,0,data scientist,na

In [72]:
df_jobs.shape

(660, 27)

## <span style="color: green;"> b.</span> Utiliza la siguiente lista de valores que serán considerados como nulos: ["na", "NA", -1, "0", "-1", "null", "n/a", "N/A", "NULL"]

Creamos nuestra variable que contendra la lista de los valores personalizados

In [73]:
valores_nulos = ["na", "NA", -1, "0", "-1", "null", "n/a", "N/A", "NULL"]

ahora que tenemos la lista, ocupamos replace para recorrer los datos buscando un match con la lista creada y transformandolo en un valor nulo.

In [75]:
jobs_reemplazado = jobs.replace(valores_nulos, np.nan)
jobs_reemplazado.head(15)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,company_age,python,excel,hadoop,spark,aws,tableau,big_data,job_simp,seniority
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,Nonprofit Organization,Insurance Carriers,...,27.0,0,0,0,0,1,0,0,data scientist,senior
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,Company - Public,Research & Development,...,52.0,0,0,1,0,0,0,1,data scientist,NaN
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,Private Practice / Firm,Consulting,...,39.0,1,1,0,0,1,0,0,data scientist,NaN
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,Company - Public,Electrical & Electronic Manufacturing,...,20.0,1,1,0,0,1,0,0,data scientist,NaN
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,Company - Private,Advertising & Marketing,...,22.0,1,1,0,0,0,0,0,data scientist,NaN
5,Data Scientist,137-171,About Us:\n\nHeadquartered in beautiful Santa ...,4.2,HG Insights,"Santa Barbara, CA","Santa Barbara, CA",51 to 200 employees,Company - Private,Computer Hardware & Software,...,10.0,1,1,1,1,0,0,0,data scientist,NaN
6,Data Scientist / Machine Learning Expert,137-171,Posting Title\nData Scientist / Machine Learni...,3.9,Novartis,"Cambridge, MA","Basel, Switzerland",10000+ employees,Company - Public,Biotech & Pharmaceuticals,...,24.0,1,0,0,0,0,0,0,data scientist,NaN
7,Data Scientist,137-171,Introduction\n\nHave you always wanted to run ...,3.5,iRobot,"Bedford, MA","Bedford, MA",1001 to 5000 employees,Company - Public,Consumer Electronics & Appliances Stores,...,30.0,1,0,0,0,0,0,0,data scientist,NaN
8,Staff Data Scientist - Analytics,137-171,Intuit is seeking a Staff Data Scientist to co...,4.4,Intuit - Data,"San Diego, CA","Mountain View, CA",5001 to 10000 employees,Company - Public,Computer Hardware & Software,...,37.0,0,0,0,0,0,0,0,data scientist,NaN
9,Data Scientist,137-171,Ready to write the best chapter of your career...,3.6,XSELL Technologies,"Chicago, IL","Chicago, IL",51 to 200 employees,Company - Private,Enterprise Software & Network Solutions,...,6.0,1,0,0,0,0,0,0,data scientist,NaN
10,Data Scientist,137-171,Join our team dedicated to developing and exec...,4.5,Novetta,"Herndon, VA","Mc Lean, VA",501 to 1000 employees,Company - Private,Enterprise Software & Network Solutions,...,8.0,1,1,0,0,1,0,0,data scientist,NaN
11,Data Scientist,137-171,About Us\n\n\nInterested in working for a huma...,4.7,1904labs,"Saint Louis, MO","Saint Louis, MO",51 to 200 employees,Company - Private,IT Services,...,4.0,1,0,0,1,0,0,0,data scientist,NaN
12,"Data Scientist - Statistics, Early Career",137-171,*Organization and Job ID**\nJob ID: 310918\n\n...,3.7,PNNL,"Richland, WA","Richland, WA",1001 to 5000 employees,Government,Energy,...,55.0,0,1,0,0,0,0,0,data scientist,NaN
13,Data Modeler,137-171,POSITION PURPOSE:\n\nThe Data Architect/Data M...,3.1,Old World Industries,"Northbrook, IL","Northbrook, IL",201 to 500 employees,Company - Private,Chemical Manufacturing,...,47.0,1,1,0,0,0,1,0,NaN,NaN
14,Data Scientist,137-171,Position Description:\n\nWant to make a differ...,3.4,Mathematica Policy Research,"Washington, DC","Princeton, NJ",1001 to 5000 employees,Company - Private,Consulting,...,34.0,1,1,0,0,1,0,0,data scientist,NaN

## <span style="color: green;"> c.</span> Elimina todas las filas con datos faltantes.

ahora que tenemos nuestra df transformada con valores nulos, podemos eliminar las filas que contengan uno.

In [82]:
jobs_reemplazado = jobs_reemplazado.dropna()
print("Tamaño actual del DataFrame:", jobs_reemplazado.shape)

Tamaño actual del DataFrame: (80, 27)

## <span style="color: green;"> d.</span> A partir de la columna “Salary Estimate”, genera dos columnas: Salario Estimado Mínimo y Máximo.

Vemos como vienen los datos

In [83]:
jobs_reemplazado["Salary Estimate"].head(10)

0      137-171
32      75-131
38      75-131
45      75-131
54      75-131
70      79-131
90      79-131
95      99-132
99      99-132
102     99-132
Name: Salary Estimate, dtype: object

agregamos columna salario estimado maximo

In [86]:
jobs_reemplazado["Salario Estimado Maximo"] = jobs_reemplazado["Salary Estimate"].apply(
    lambda x: int(x.split("-")[1]) * 1000 ## con esto ya queda respondida la necesidad
    if isinstance(x, str) and "-" in x else np.nan ## pero le agregue esto porque me parece una buena practica interesante
)                         #en si, lo que hace esta parte del codigo es que se pregunta si x es string y contiene un "-", si no, lo devolvera como NaN

agregamos columna salario estimado minimo

In [87]:
jobs_reemplazado["Salario Estimado Minimo"] = jobs_reemplazado["Salary Estimate"].apply(
    lambda x: int(x.split("-")[0]) * 1000 
    if isinstance(x, str) and "-" in x else np.nan
)

verificamos como quedo la agregación de columnas

In [88]:
jobs_reemplazado.head(10)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Type of ownership,Industry,...,excel,hadoop,spark,aws,tableau,big_data,job_simp,seniority,Salario Estimado Minimo,Salario Estimado Maximo
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,Nonprofit Organization,Insurance Carriers,...,0,0,0,1,0,0,data scientist,senior,137000,171000
32,Senior Research Statistician- Data Scientist,75-131,Acuity is seeking a Senior Research Statistici...,4.8,Acuity Insurance,"Sheboygan, WI","Sheboygan, WI",1001 to 5000 employees,Company - Private,Insurance Carriers,...,0,0,0,0,0,0,data scientist,senior,75000,131000
38,Senior Analyst/Data Scientist,75-131,At Edmunds were driven to make car buying easi...,3.4,Edmunds.com,"Santa Monica, CA","Santa Monica, CA",501 to 1000 employees,Company - Private,Internet,...,1,0,0,1,1,0,data scientist,senior,75000,131000
45,Senior Data Scientist,75-131,Klaviyo is looking for Senior Data Scientists ...,4.8,Klaviyo,"Boston, MA","Boston, MA",201 to 500 employees,Company - Private,Computer Hardware & Software,...,0,0,0,0,0,0,data scientist,senior,75000,131000
54,Senior Data Scientist,75-131,Benson Hill empowers innovators to develop mor...,3.5,Benson Hill,"Saint Louis, MO","Saint Louis, MO",201 to 500 employees,Company - Private,Biotech & Pharmaceuticals,...,1,0,0,0,0,1,data scientist,senior,75000,131000
70,Principal Data Scientist,79-131,Job Requisition ID #\n20WD40121\nJob Title\nPr...,4.0,Autodesk,"San Francisco, CA","San Rafael, CA",5001 to 10000 employees,Company - Public,Computer Hardware & Software,...,1,1,1,1,0,1,data scientist,senior,79000,131000
90,Senior Data Scientist,79-131,"Secure our Nation, Ignite your Future\n\nJob S...",4.2,ManTech,"Alexandria, VA","Herndon, VA",5001 to 10000 employees,Company - Public,Research & Development,...,0,1,1,0,1,1,data scientist,senior,79000,131000
95,Senior Data Scientist,99-132,"About Us\n\nAt GutCheck, we pioneered agile ma...",3.8,GutCheck,"Denver, CO","Denver, CO",51 to 200 employees,Company - Private,Advertising & Marketing,...,0,0,0,0,0,0,data scientist,senior,99000,132000
99,Senior Data Scientist,99-132,Job Requisition ID #\n20WD40666\nJob Title\nSe...,4.0,Autodesk,"San Francisco, CA","San Rafael, CA",5001 to 10000 employees,Company - Public,Computer Hardware & Software,...,0,1,1,0,0,1,data scientist,senior,99000,132000
102,Sr Data Engineer (Sr BI Developer),99-132,Description/Responsibilities\n\n\nResponsible ...,3.2,Tivity Health,"Chandler, AZ","Franklin, TN",501 to 1000 employees,Company - Public,Health Care Services & Hospitals,...,0,1,0,0,0,1,data engineer,senior,99000,132000

## <span style="color: green;"> e.</span> Realiza la recodificación de la columna Size con los valores de la siguiente tabla

| Size                    | Descripción                 |
|--------------------------|-----------------------------|
| 10000+ employees         | Mega Empresas               |
| 5001 to 10000 employees  | Grandes Empresas            |
| 1001 to 5000 employees   | Medianas Empresas           |
| 201 to 500 employees     | Pequeñas Empresas           |
| 51 to 200 employees      | Pequeñas Grandes Empresas   |
| 501 to 1000 employees    | Microempresas               |
| Unknown                  | Empresas sin Información    |

In [90]:
diccionario = {
    "10000+ employees": "Mega Empresas",
    "5001 to 10000 employees": "Grandes Empresas",
    "1001 to 5000 employees": "Medianas Empresas",
    "201 to 500 employees": "Pequeñas Empresas",
    "51 to 200 employees": "Pequeñas Grandes Empresas",
    "501 to 1000 employees": "Microempresas",
    "Unknown": "Empresas sin Información"
}

Aplicar el reemplazo usando el diccionario

In [93]:
jobs_reemplazado["Size"] = jobs_reemplazado["Size"].replace(diccionario)

In [95]:
jobs_reemplazado[["Size"]].head(10)

                          Size
0            Medianas Empresas
32           Medianas Empresas
38               Microempresas
45           Pequeñas Empresas
54           Pequeñas Empresas
70            Grandes Empresas
90            Grandes Empresas
95   Pequeñas Grandes Empresas
99            Grandes Empresas
102              Microempresas

## <span style="color: green;"> f.</span> Finalmente, genera una tabla pivote que muestre la media del salario estimado mínimo y la media del salario estimado máximo por tamaño de empresa

In [99]:
tabla_pivote_salarios = pd.pivot_table(
    jobs_reemplazado,
    index="Size",  # Filas -> tamaño de empresa
    values=["Salario Estimado Minimo", "Salario Estimado Maximo"],  # Qué calcular
    aggfunc="mean"  # Qué operación aplicar -> promedio
)
tabla_pivote_salarios.head()

                          Salario Estimado Maximo  Salario Estimado Minimo
Size
Empresas sin Información            110500.000000             73000.000000
Grandes Empresas                    138875.000000             92125.000000
Medianas Empresas                   137461.538462             93923.076923
Mega Empresas                       151111.111111             97888.888889
Microempresas                       146235.294118            100176.470588

y agregamos un detalle para que se vea mejor, para eso redondeamos la cifra

In [100]:
tabla_pivote_salarios = tabla_pivote_salarios.round(0)
tabla_pivote_salarios.head()

                          Salario Estimado Maximo  Salario Estimado Minimo
Size
Empresas sin Información                 110500.0                  73000.0
Grandes Empresas                         138875.0                  92125.0
Medianas Empresas                        137462.0                  93923.0
Mega Empresas                            151111.0                  97889.0
Microempresas                            146235.0                 100176.0